application: wixoss-tcg
version: 1-0-0
runtime: go
api_version: go1
skip_files:
  - ^(.*/)?.*/node_modules/.*
  - ^(.*/)?.*/test/.*

handlers:

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /view/(.*\.html)
  static_files: static/view/\1
  upload: static/view/(.*\.html)

- url: /view/admin/(.*\.html)
  static_files: static/view/admin/\1
  login: admin
  upload: static/view/admin/(.*\.html)

- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/img/(.*\.(gif|png|jpg))

- url: /(favicon.ico)
  static_files: static/img/\1
  upload: static/img/favicon.ico

- url: /css/(.*\.css)
  static_files: static/css/\1
  upload: static/css/(.*\.css)

- url: /js/(.*\.js)
  static_files: static/js/\1
  upload: static/js/(.*\.js)

- url: /font/(.*\.(eot|svg|ttf|woff))
  static_files: static/font/\1
  upload: static/font/(.*\.(eot|svg|ttf|woff))

- url: /api/.*
  script: _go_app

- url: /api/admin/.*
  login: admin
  script: _go_app